defaults:
  - _self_

monitor:
  metric: "val/acc_top1"
  mode: "max"

geometry_preserving: true
leaky_relu_negative_slope: 0.0
candidate_idx: 0
retrieval_mode: "preselected"
preselected_num_candidates: 10

mimic_root: "/sc-resources/dh-mimic/mimic_iv_2_2"
train_split_csv: "/sc-resources/dh-mimic/mimic_iv_2_2/contrastive_learning/data/folds/fold_0/train.csv"
val_split_csv: "/sc-resources/dh-mimic/mimic_iv_2_2/contrastive_learning/data/folds/fold_0/val.csv"
test_split_csv: "/sc-resources/dh-mimic/mimic_iv_2_2/contrastive_learning/data/folds/fold_0/test.csv"

load_radiology_text: true
require_all_modalities: false
radiology_chunk_size: 250000
num_workers: 4

radiology:
  text_model_id: StanfordAIMI/RadBERT
  proj_hidden_dim: 512
  dropout: 0.0
  max_text_length: 256
  lora: False

timeseries:
  input_dim: 192
  mlp:
    hidden_dims: [512, 512]
    hidden_dropouts: [0.1, 0.1]

demographics:
  input_dim: 5
  mlp:
    hidden_dims: [128, 256]
    hidden_dropouts: [0.1, 0.1]
