defaults:
 - plugins: debug
 - _self_

# "/path/to/anonymized/splits_0.yaml"
# "/path/to/anonymized/splits_1.yaml"
# "/path/to/anonymized/splits_2.yaml"
# "/path/to/anonymized/splits_3.yaml"
# "/path/to/anonymized/splits_4.yaml"

splits: /path/to/anonymized/splits_0.yaml  # /path/to/anonymized/splits_0.yaml
#splits: /path/to/anonymized/split_0.yaml
train_split: 'train'
valid_split: 'valid'
test_split: 'test'
combine_eids_as: 'intersect'  # 'intersect' / 'union' 
num_workers: 4  # 32
batch_size: 48  # 3072  # 512
pin_memory: true
drop_last: true
shuffle: true
keyerr: true  # true if intersect, false if union