defaults:
 - plugins: default
 - _self_

splits: /sc-projects/sc-proj-ukb-cvd/projects/data/ukb/cvsplits/splits_0.yaml
train_split: 'train'
valid_split: 'valid'
test_split: 'test'
combine_eids_as: 'intersect'  # 'intersect' / 'union' 
num_workers: 4  # 32
batch_size: 256  # 3072  # 512
pin_memory: true
drop_last: true
shuffle: true
keyerr: true  # true if intersect, false if union