defaults:
  - _self_
  - datamodule: nmr_retrieval_2
  - encoders: ukb_nmr_retrieval_2  # symile_mimic / symile_m3 / ukb
  - modelname: sigmile  # clip / symile / sigmile

dataset_name: ukb  # symile_mimic / symile_m3 / ukb
batch_size: 512
split_nr: 1
devices: 1

optimizer:
  name: schedulefree_adamw  # 
  lr: 1e-2
  lr_gate_mul: 1.0
  warmup_steps: 100
  weight_decay: 0.01  # 1e-4
  eps: 1e-7
  betas: [0.9, 0.95]

seed: 420

precision: "bf16"
max_epochs: 25
patience: 5
monitor: "val/acc_top1"
monitor_mode: "max"
wandb:
  project: "sigmile"
  group: None
